account_id = "7acd7efa192c36ccdf17b47f6074276c"
compatibility_date = "2024-12-01"
main = "workers-site/index.js"
zone_id = "46013848ddd6e0a3434c9d96f4bc5db1"

[site]
bucket = "./dist"

[env.staging]
name = "dat"
vars = {WORKER_ENV = "staging"}
workers_dev = true

[env.production]
name = "dat-production"
route = "dat.coolkidscomputer.club/*"
vars = {WORKER_ENV = "production"}
