account_id = "7acd7efa192c36ccdf17b47f6074276c"
type = "webpack"
zone_id = "46013848ddd6e0a3434c9d96f4bc5db1"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.staging]
name = "dat"
vars = {WORKER_ENV = "staging"}
workers_dev = true

[env.production]
name = "dat-production"
route = "dat.coolkidscomputer.club/*"
vars = {WORKER_ENV = "production"}
