name: Auto-Archive
description: Notify Internet Archive of Content Updates
inputs:
  sitemap:
    description: Filepath of sitemap
    required: true
    default: 'dist/sitemap.xml'
  manifest:
    description: Filepath of manifest file (written to by this action)
    required: true
    default: 'internet-archive.json'
  dry_run:
    description: Run the action without hitting the Internet Archive API
    required: false
    default: 'false'
runs:
  using: node12
  main: index.js
