name: Lint, Build, and Deploy (Production)

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10

    env:
      CI: 'true'
      SITE_ENV: 'production'
      DEPLOY_URL: 'https://dat.coolkidscomputer.club/'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure NPM
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        echo '@saulhardman:registry=https://npm.pkg.github.com' >> .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    - name: Install Dependencies
      uses: bahmutov/npm-install@v1

    - name: Lint Source Files
      run: yarn lint

    - name: Run Static Site Generator (Production)
      run: yarn build
      env:
        NODE_ENV: production

    - name: Deploy to Cloudflare (Production)
      env:
        CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        npx wranger deploy --env production

    - name: Update Internet Archive
      uses: ./.github/actions/auto-archive

    - name: Commit Internet Archive Manifest
      uses: EndBug/add-and-commit@v4
      with:
        message: 'chore(CI): update internet archive manifest'
        add: internet-archive.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
